package kuehne.nagel.utils;

public enum DatabaseFailures {
    TYPO_APPLICATION_PROPERTIES_FILE_NAME,
    APPLICATION_PROPERTIES_FILE_FAILURE,
    NO_TOPIC,
    INVALID_SQL_QUERY,
    NO_TOPIC_OR_QUESTION,
    DATA_DUPLICATE
}
